# https://aka.ms/yaml
variables:
  - group: Keys
trigger: 
  paths:
    exclude:
      - ReleaseNotesHistory/History.csv
      - ReleaseNotesHistory/ReadMe.md
      - ReadMe.md
      - .github/Azure-pipeline.yml
  branches:   
    include:
      - master
pool:
  vmImage: windows-2019
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  displayName: Release
  inputs:
    pwsh: true
    targetType: filePath
    filePath: .\.github\Azure-Pipeline.ps1
    arguments: $(Build.Repository.Name) $(DXApiFeed) $(NuGetApiKey) $(build.artifactstagingdirectory) $(BetaFeed)
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Xpand.v$(Build.BuildNumber)'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'Xpand.v$(Build.BuildNumber)'




