# These are supported funding model platforms

open_collective: expand
custom: [StarXpandRepo.expandframework.com](https://github.com/eXpandFramework/eXpand/stargazers),[architect: Apostols Bekiaris](https://github.com/apobekiaris)

